name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO(ZhaoYingkai)
      - name: auto ui-test
        run: echo uitest

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build
      
      - name: scp deploy
        run: |
          echo ${{ secrets.DEPLOY_KEY }} > ~/.ssh/deploy_key
          scp -P 222 -r ./dist/* teapot@114.116.213.123:~/wwwroot/wespace/
