name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO(ZhaoYingkai)
      - name: auto ui-test
        run: echo uitest

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build
      
      - name: deployment
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
