name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO(ZhaoYingkai)
      - name: auto ui-test
        run: echo uitest

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build
      
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-P 222 -r "
          REMOTE_HOST: 114.116.213.123
          REMOTE_USER: teapot
          SOURCE: './dist/*'
          TARGET: '~/wwwroot/wespace/'
