name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO(ZhaoYingkai)
      - name: auto ui-test
        run: echo uitest

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build
      
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 114.116.213.123
          username: teapot
          port: 222
          key: ${{ secrets.DEPLOY_KEY }}
          source: ./dist/*
          target: ~/wwwroot/wespace/
