name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO(ZhaoYingkai)
      - name: auto ui-test
        run: echo uitest

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build
      
      - name: scp-deployer
        uses: siva1024/scp-deployer@v1.0
        with:
          host: "114.116.213.123"
          username: "teapot"
          port: "222"
          password: "HTTP 418 I'm a teapot."
          source: "./dist/*"
          target: "~/wwwroot/wespace/"
